name: SpacePush
on: [push]
env: 
  SPACE_ACCESS_TOKEN: ${{ secrets.SPACE_SECRET }}
jobs:
  deploy:
      name: Push to space
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - id: create_dot_space
          run: mkdir .space
        - id: add_meta
          run: curl ${{ secrets.META_FILE }} -o .space/meta
        - id: space_cli
          run: |
            curl -fsSL https://get.deta.dev/space-cli.sh | sh
            echo '/home/runner/.detaspace/bin' >> $GITHUB_PATH
        - id: dir
          run: ls
        - id: deploy
          shell: bash
          run: |
            space push